name: Open URL in Chrome

on:
  workflow_dispatch:  # Allows manual start

jobs:
  open_url:
    runs-on: ubuntu-latest
    steps:
      - name: Install Chrome & Dependencies
        run: |
          sudo apt update
          sudo apt install -y wget unzip xvfb
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome-stable_current_amd64.deb || sudo apt -f install -y
          google-chrome --version

      - name: Install Python & Selenium
        run: |
          pip install selenium webdriver-manager

      - name: Run Selenium Script
        run: |
          echo "Opening URL in Chrome..."
          python - <<EOF
          from selenium import webdriver
          from selenium.webdriver.chrome.service import Service
          from webdriver_manager.chrome import ChromeDriverManager

          options = webdriver.ChromeOptions()
          options.add_argument("--headless")  # Run without UI
          options.add_argument("--no-sandbox")
          options.add_argument("--disable-dev-shm-usage")

          service = Service(ChromeDriverManager().install())
          driver = webdriver.Chrome(service=service, options=options)
          driver.get("https://cdn.qw03.xyz/h/910001002.html?code=31WC3Q&uid=130159769")
          print("Page opened successfully!")
          driver.quit()
          EOF
